version: '3'

services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=dataService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    #    healthcheck:
    #      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d dataService'" ]
    #      interval: 10s
    #      timeout: 3s
    #      retries: 3
    ports:
      - "5432:5432"

  data-service:
    restart: on-failure
    container_name: data-service
    image: ivandvurechenskiy/data-service:latest
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dataService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"

  sender-service:
    container_name: sender-service
    image: ilyakorobko/new-sender-service:latest
    depends_on:
      - kafka
      - send-manager
    environment:
      TZ: Europe/Moscow
      SPRING_KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

  send-manager:
    container_name: send-manager
    image: ivandvurechenskiy/new-send-manager:latest
    depends_on:
      - kafka
      - data-service
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      rest_address: http://data-service:8080/order
      TZ: Europe/Moscow
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

