version: '3.9'

services:

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=dataService
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Moscow
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d dataService'" ]
      interval: 15s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  data-service:
    restart: on-failure
    container_name: data-service
    image: ivandvurechenskiy/data-service:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dataService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"

  sender-service:
    container_name: sender-service
    image: someimage:latest
    depends_on:
      kafka:
        condition: service_healthy
      send-manager:
        condition: service_started
    environment:
      TZ: Europe/Moscow
      SPRING_KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

  send-manager:
    container_name: send-manager
    image: someimage:latest
    depends_on:
      kafka:
        condition: service_healthy
      data-service:
        condition: service_started
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      rest_address: http://data-service:8080/order
      rest_callback_address: http://data-service:8080/schedule
      TZ: Europe/Moscow

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 40s
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ivan5656@list.ru
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "80:80"